[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.13"

block_gas_limit = 31000000
gas_price = 2000000000

[etherscan]
fantom = { key = "${FANTOMSCAN_API_KEY}", url = "https://api-testnet.ftmscan.com/api" }

# See more config options https://github.com/gakonst/foundry/tree/master/config